version: 2
jobs:
  test:
    docker:
      - image: node:11

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-

      - run:
          name: Install Deps
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Codegen
          command: yarn query-codegen

      - run:
          name: Typescript Check
          command: yarn tsc

      - run:
          name: TSLint
          command: yarn tslint

      - run:
          name: Code Style Lint
          command: yarn check-fmt

      - run:
          name: Run Tests
          command: yarn test --coverage

      - run:
          name: Build
          command: yarn build

      - run:
          name: Compress Build Artifacts
          command: tar czvf forte-web.tar.gz -C build .

      - persist_to_workspace:
          root: .
          paths:
            - ./forte-web.tar.gz

  deploy_artifacts:
    docker:
      - image: garland/aws-cli-docker:1.15.47

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Upload to S3
          command: |
            FOLDER_NAME=$([ -z "$CIRCLE_TAG" ] && echo "$CIRCLE_BRANCH" || echo "$CIRCLE_TAG")
            aws s3 cp ./forte-web.tar.gz "s3://forte-web-artifacts/${FOLDER_NAME}/forte-web.tar.gz"

workflows:
  version: 2
  test:
    jobs:
      - test

      - deploy_artifacts:
          requires:
            - test

          filters:
            # Disable on PR builds. Pull Request builds have branch names of
            # pull/<pull request number>. If this changes, our builds will fail
            # (without leaking our secrets) since secrets aren't exposed to PR
            # builds.
            branches:
              only: /^(?!pull\/).*$/

      - deploy_surge:
          requires:
            - test
          filters:
            branches:
              only: master